### PR TITLE
Sort PlanSummaryData items by time

### LINKED ISSUE #106: Sort tasks by time
Hi
When I create my task template I separate what want to do (Read article, write report) every day from random interuption tasks (buy this, fetch that, email this person, etc.) or meetings. They are all given a time, but when shown on the timeline, they are in the order of the list and not TIME. Would it be possible for the day planner to read the time and slot the items accordingly in my timeline?

### PR DESCRIPTION
**Pull request by flaper87**
This commit makes sure that all PanItems are sorted by timne in the
summary data. This allows for having separate sections with time slots
throughout the note and still have them presented organzied in the
timeline.

image

Fixes #106

### CODE REVIEW

**Comment by sierxue** [comment]
I'm using the day-planner plugin with version number 0.5.8. Items are not sorted by time. Does that mean the version I'm using does not include the commit?

**Comment by flaper87** [comment]
> I'm using the day-planner plugin with version number 0.5.8. Items are not sorted by time. Does that mean the version I'm using does not include the commit?

Correct! This PR hasn't been merged so I don't think you have it :) 

You can apply it manually if you want it today.

**Comment by sierxue** [comment]
@flaper87 Perfect! It works.

**Comment by csss1234** [comment]
> 

I'd like this feature so much but afraid I don't know how to apply it manually. I'm not a coder. I tried downloading the source code and changed the appropriate file, but after an hour of googling, I still don't know how to build it into the "main.js" format that obsidian is looking for. 

I checked your forked repo but it doesn't have any "Releases". 

Any tips? I'm on a mac, and have typescript installed.

**Comment by jerryhcooke** [comment]
@csss1234 

Assuming you're using standard file structure:

**Go to** 
_.obsidian\Plugins\obsidian-day-planner_ 
**Open**
 _main.js_
**Find**
 _this.items = items_
**Modify that line to read**  
_this.items = items.sort((a, b) => (a.time < b.time ? -1 : 1));_

**Comment by ivan-lednev** [comment]
Closing this, since the issue is already fixed in 0.7.0

**Pull request closed without merging**
