### PR TITLE
Add setting to be able to load specific markdown template

### PR DESCRIPTION
**Pull request by aitorllj93**
Add setting to be able to load specific markdown template.

**Important**: I haven't included tests and currently I don't have intentions on adding them, I just modified the code to make it work based on my personal needs and using manual installation until this feature is available on the plugin.

### CODE REVIEW

**Comment by zdway10** [comment]
hello, I want to load specific markdown template. it's great to know you done it. And I had downloaded those 4 changed files with updates. Question: How can i enable it ? need I update the main.js ?  thanks in advanve.

**Comment by zdway10** [comment]
hello, I want to load specific markdown template. it's great to know you done it. And I had downloaded those 4 changed files with updates. Question: How can i enable it ? need I update the main.js ?  thanks in advanve.

**Comment by d3v0ps** [comment]
Hi @zdway10 you must replace the plugin in your local with the one in this PR, I can't remember how I did because I haven't it in my current setup but as far as I remember it has an extra build step in order to get the final files (from ts to js). Once you have it running you will have an extra option in the plugins settings section to setup the template you want

**Comment by zdway10** [comment]
> Hi @zdway10 you must replace the plugin in your local with the one in this PR, I can't remember how I did because I haven't it in my current setup but as far as I remember it has an extra build step in order to get the final files (from ts to js). Once you have it running you will have an extra option in the plugins settings section to setup the template you want.
> 
> If I'm honest, I wouldn't use this plugin as it's pretty abandoned, this PR was created 6 months ago and no answer from the author, also the repo has 74 issues opened and most of them aren't being answered by the repo owner

Got it, thanks a lot, Bro @d3v0ps

**Comment by ivan-lednev** [comment]
Closing this as stale. If you think this is still a valuable addition, please create an issue where we can discuss implementation.

**Pull request closed without merging**
