### PR TITLE
Daily mode

### LINKED ISSUE #114: Daily mode
I would love to be able to just set a mode where the day planner pane is automatically linked to my daily note so I don't have to manually link it every day. I end up having to do it on desktop and mobile. I would just want it to only show content for today's daily note and not generate empty files in the Day Planner folder.

### PR DESCRIPTION
**Pull request by teaqu**
Allows Day Planner to automatically link to the current [daily note](https://help.obsidian.md/Plugins/Daily+notes).

Fixes #114

### CODE REVIEW

**Comment by wvffle** [comment]
@lynchjames would you mind taking a look at this PR? It seems like it is a pretty requested feature

**Comment by Kitefr** [comment]
@teaqu Nice PR. But shouldn't the plugin for daily note be added as a `peerDependencies` instead ? As this is an optional feature.

**Comment by teaqu** [comment]
Hey @Kitefr nice to learn about peer dependencies, I haven't come across them before. I'm still not sure I quite understand them but I think maybe not in this case. This pull request would create a hard requirement on obsidian-daily-notes-interface which is actually a is a small library for interacting with the daily notes plug-in, not the actual plug-in itself (https://github.com/liamcain/obsidian-daily-notes-interface).

**Comment by Kitefr** [comment]
`peerDependencies` means that in that case, if you want this part to work, you should have the plugin `daily notes` installed but it is up to the user to install it. It should not be included in this plugin as this plugins only mention to use it is it is available.
But as this is for the interface, It might be correct.

**Comment by aviaryan** [comment]
What is the status of this project @lynchjames? The last commit is 1.5 years ago. Thanks.

**Comment by replete** [comment]
@lynchjames I understand you've probably moved on, but this is such a popular community plugin I was wondering if you'd consider a maintenance spike to merge a few PRs like this one?

It's popular enough that people would probably chip in to fund some maintenance, if you showed a 'fundraiser tracker' somewhere to show that you'll work on it for some amount of time after hitting donation milestones, I think many would chip in to move things along. 

Thanks for the work on this, its a great plugin.

**Comment by replete** [comment]
@teaqu I forked the main repo, checked out your `daily-mode` branch, merged, and `npm run dev`

I got this error:
```shell
$ npm run build

> obsidian-day-planner@0.5.8 build
> rollup --config rollup.config.js


src/main.ts → dist/...
(!) Plugin typescript: @rollup/plugin-typescript TS2339: Property 'sourceMode' does not exist on type 'MarkdownView'.
src/planner-md.ts: (34:34)

34         const currentLine = view.sourceMode.cmEditor.getCursor().line;
```

(that may just be a missing Typescript definition)

Then, I swapped the `dist/main.js` and put it into my vault's `plugins/obsidian-day-planner`, set the GUI mode option to `Daily mode` and nothing happens.

I then tried deleting the original plugin, and creating a new folder composed of`dist/main.js`, and `manifest.json` and `styles.css` from `test-vault/.obsidian/plugins/obsidian-day-planner` with the same result. No planner data in daily notes.

Any ideas?

**Comment by replete** [comment]
I've just realized as a requirement for something else, probably `Periodic Notes` (in order to get weekly notes) meant that Daily Notes was disabled. I'll have a poke around and see exactly what's causing that.

**Comment by replete** [comment]
This seems to break command mode, anyways I'm going to move back back to the dead plugin and command mode for now. Maybe someone will come along and revive this plugin in the future!

**Comment by replete** [comment]
Pulled a fork and merged this, works well!

**Comment by SalahAdDin** [comment]
@replete Are you thinking of adding a timer/stop watcher to track the time?

It would be awesome!

**Comment by replete** [comment]
> @replete Are you thinking of adding a timer/stop watcher to track the time?
> 
> It would be awesome!

That's a pretty cool idea. A focus timer. How do you think it should work? As a special task item?
```
- [ ] 09:00 Work on thing
- [ ] 09:20 Focus (timer: 25:00) 
```

I might actually make some changes to the UI, I've already redesigned it with CSS (snippet link in README.md):

dayplanner styles

**Comment by SalahAdDin** [comment]
> > @replete Are you thinking of adding a timer/stop watcher to track the time?
> > It would be awesome!
> 
> That's a pretty cool idea. A focus timer. How do you think it should work? As a special task item?
> 
> ```
> - [ ] 09:00 Work on thing
> - [ ] 09:20 Focus (timer: 25:00) 
> ```
> 
> I might actually make some changes to the UI, I've already redesigned it with CSS (snippet link in README.md):
> 
> dayplanner styles [ dayplanner styles ](https://camo.githubusercontent.com/5468c53c397072058163cf2a4c38b7e9a3fea271d0d1fcdc124b268fe2e45c07/68747470733a2f2f692e696d6775722e636f6d2f784664624977652e676966) [ ](https://camo.githubusercontent.com/5468c53c397072058163cf2a4c38b7e9a3fea271d0d1fcdc124b268fe2e45c07/68747470733a2f2f692e696d6775722e636f6d2f784664624977652e676966)

Is this plugin creating daily plans from the calendar itself? Like replacing daily notes?

It would me a small stop watch widget either in the planer panel title or in the bottom toolbar too, what do you think?

**Comment by replete** [comment]
image

I was thinking a subtask with prominent timer that shows up like this perhaps, maybe more prominent

**Comment by replete** [comment]
@SalahAdDin No, this is just a screenshot that happened to show the day planner CSS changes I made. It works on the checklist items under 'Day Planner' heading in daily notes as expected..

**Comment by replete** [comment]
image

```
- [ ] 10:30 Work on Obsidian Daily
- [ ] 11:30 (25:00) Focus
- [ ] 12:00 Breakfast
- [ ] 12:30 GTD Obsidian
```

I need to think about it a bit more, but I like the idea

**Comment by replete** [comment]
@SalahAdDin I'm probably going to add this feature to my fork, in which I've merged the other useful PRs.

If you'd like to continue this conversation and feed into the development process, [comment in this Feature issue](https://github.com/replete/obsidian-day-planner/issues/2)

-Phil

**Comment by SalahAdDin** [comment]
@replete it seems @ivan-lednev updated it!!!

**Comment by ivan-lednev** [comment]
Yup, I've been working on a fork for a while, rewriting almost all of it. James Lynch contacted me and transferred ownership of the original repo. PRs and issues are welcome.

**Comment by replete** [comment]
@ivan-lednev That's great to hear Ivan, I forked it with intent to fix it but it just hasn't happened. I'll check your version out and probably forward people on

**Pull request merged**
