### PR TITLE
feat: reorder tasks in the Markdown file based on their time

### LINKED ISSUE #386: [Feature request] Sort tasks by time in daily note after moving in timeline
Hey! Thanks for this great plugin which I use daily!

One feature I would appreciate is adding a way to sort tasks by their time after altering the day timeline.

I see there is some code for it already in https://github.com/ivan-lednev/obsidian-day-planner/blob/6bc7d6f993754c6f5c0dc24f8600190cadb7788f/src/mdast/mdast.test.ts#L56-L70 but looks like that's commented out and not working. This code correctly explains what I want to achieve - after moving a task in the day planner timeline, I would love it if it was also moved in the markdown file, so the task list in the file would be chronological.

I can also help out with this feature if you let me know which pieces of code I should look into. I haven't contributed to Obsidian plugins yet, and I am a frontend engineer and I hope I can help out 🙂

### PR DESCRIPTION
**Pull request by Gelio**
This PR adds support for reordering the task in the Markdown file by their start time as an opt-in experimental feature.

Closes #386

## Reordering tasks after moving them in the planner

When the `reorderTasksAfterMoving` setting is enabled, each task moved inside the same day in the day planner timeline will be automatically also moved in the Markdown document for that timeline, so tasks appear chronologically in the list (see the _Task order_ section below for a longer explanation).

Only the tasks moved in the timeline will be moved in the Markdown document. Other tasks will be left as they are, even if they are not ordered.

https://github.com/ivan-lednev/obsidian-day-planner/assets/889383/a8c42102-d881-44d5-ab1d-5bfd858749d2

<details>

<summary>Markdown document used in the video</summary>

Some tasks are in the wrong order in the document at the start. They will be put into the right place when they are moved.

```md
# Day planner

- [ ] 09:00 - 09:30 Sleep

- [ ] 07:30 - 09:00 Another task
    Updating again

- [ ] 09:30 - 10:00 Item without time

- [ ] 10:00 - 10:30 Some final item

- [ ] 10:10 - 11:10 Wake up

- [ ] 10:30 - 11:00 Misplaced item

    With more content inside.

- [ ] 12:40 - 13:10 Fix something
    Part of "fix something"

- [ ] 11:40 - 12:40 Eat breakfast

    I should not eat as long.
```

</details>

## Editor command to reorder the tasks

Aside from reordering the items as they are being moved in the timeline, there is also a new _Reorder tasks by time_ editor command. It reorders all the tasks in the day-planner heading's first list.

This is done so the user can keep a chronological order of tasks if they changed the start/end times in the document directly and don't want to manually move the task items to have a chronological order.

https://github.com/ivan-lednev/obsidian-day-planner/assets/889383/aa2fc6b3-f240-4b8c-a0e5-edfa4488038c

<summary>Markdown document used in the video</summary>

This is the same Markdown document as in the previous video.

Some tasks are in the wrong order in the document at the start. They will be put into the right place when the command is executed.

```md
# Day planner

- [ ] 09:00 - 09:30 Sleep

- [ ] 07:30 - 09:00 Another task
    Updating again

- [ ] 09:30 - 10:00 Item without time

- [ ] 10:00 - 10:30 Some final item

- [ ] 10:10 - 11:10 Wake up

- [ ] 10:30 - 11:00 Misplaced item

    With more content inside.

- [ ] 12:40 - 13:10 Fix something
    Part of "fix something"

- [ ] 11:40 - 12:40 Eat breakfast

    I should not eat as long.
```

</details>

## Saving the mdast tree back to the file

It is possible that the mdast's `toMarkdown` function will produce different formatting than the initial one from the user.

I don't think there is much we can do about it. The sooner users start using this feature and adhere to the format produced by `toMarkdown`, the better. Also, maybe users do not care about the specific format of their Markdown task lists, and are fine with using a different number of spaces, or having newlines around items.

## Task order

The task order is defined in `compareTaskStartEndTime`.

The tasks are ordered by their start time, chronologically.

If they have the same start time, they are then ordered by their end times, also chronologically (tasks that end sooner will appear before tasks that end later). Tasks without an end time will appear before tasks with end time.

List items without time are left as they are.

## Detecting lists

The code that reorders tasks operates on a single `List` from `mdast`. This means that it can only reorder items inside a single consecutive list.

If there are multiple lists inside the planner heading, the code will only operate on the first one (in the case of the _Reorder tasks by time_ command), or the one where the edited task is (in the case of editing the tasks in the timeline).

This can appear as broken in the following Markdown document, where there are 2 separate lists inside the _Day planner_ heading:

```md
## Day planner

- [ ] 9:00 Something here

Top level item here.

- [ ] 10:00 A new item. This is also a new list, according to mdast
```

The reordering will work fine if this is a single list (the "top level" item description becomes a paragraph inside the first list item):

```md
## Day planner

- [ ] 9:00 Something here

   Top level item here.

- [ ] 10:00 A new item. This is also a new list, according to mdast
```

### CODE REVIEW

**Comment by ivan-lednev** [comment]
Hello, @Gelio, thanks for the submission! This one is pretty big, so once I have a bit more free time on my hands, I'll take a look.

**Comment by Gelio** [comment]
Hi @ivan-lednev , no problem, take your time. I'm receptive to feedback once you have some

**Comment by wrgrant** [comment]
Ooh, this is neat. I'm sure we all manually use a lot of Alt + Up/Down to move the tasks around after adjusting in the day plan UI. This will save a lot of time for those excessively detail oriented among us haha.

**Comment by ShiqiRao** [comment]
Great work! That is what I want!

**Comment by Gelio** [comment]
Hey @ivan-lednev, is there anything I can do to help get this change merged sooner?

**Comment by ivan-lednev** [comment]
Hey @Gelio, sorry for keeping you in the dark there. The reason it's taking me so long is that I don't have a lot of capacity right now, and reviewing other people's PRs is more like a job than a fun hobby. That's why you might see me making other changes and not doing the review 🤪 These two things are very different for me. I'll get to it eventually.

**Comment by Gelio** [comment]
Thanks for the reply. I can only sympathize. Take care 🙂

**Comment by Esser50K** [comment]
Plus 1 on this feature 👍

**Comment by ceciliamay** [comment]
bumping this one because i reorder my tasks a lot and i think this would be very helpful!

**Comment by ivan-lednev** [comment]
Hey, @Gelio, I hijacked your PR and massaged it a bit, but I'm happy to say that this feature has been finally merged 😊 Thanks for your input!

**Comment by Gelio** [comment]
Great, thanks! I'm looking forward to using it in a new version 🚀

**Pull request merged**
