### PR TITLE
Add 'colorful' timeline

### PR DESCRIPTION
**Pull request by JosephBrooksbank**
adds back an optional gradient to the timeline.

This was a feature in the 'OG' version of Day Planner.
In the original version, there was a collection of 10 pre selected colors, and the tasks would just increment, rolling over eventually, leading to the gradient resetting. 

I opted to programmatically create the gradient instead. This leads to less visually distinct colors, but is simpler with multiple tasks overlapping, and creates a continuous gradient. It is enabled via settings and the colors can be chosen.

Let me know what you think. The 'finished' task text color can be difficult to read on some colors. In the future I'd like to use a contrast calculation to change the text color as appropriate, but I wanted to get thoughts on this first.

### CODE REVIEW

**Comment by ivan-lednev** [comment]
Hello, @JosephBrooksbank, thank you for the submission. I'll test this out and give you my thoughts shortly.

**Comment by ivan-lednev** [comment]
Hello, @JosephBrooksbank,

Thanks for taking the time to create a PR. I'm personally not planning to use or support this feature, but I don't mind merging it.

But first, there is some stuff to do:
- [ ] Make sure it looks good in both dark & light themes and add some screenshots
- [ ] Make sure check-boxes also look good (check out 0.8.0 that uses Obsidian's check boxes for tasks) and add some screenshots
- [ ] Rebase and resolve conflicts

Also, have you considered coloring blocks based on time, not on their order? This might be optional.

**Comment by JosephBrooksbank** [comment]
Hi, I'll get on those changes, thanks for the feedback!

Could you describe more what you mean about 'coloring blocks based on time, not on their order'? Like based on how long they take? Currently, the color of any individual block is based on the time the block starts, expressed as a percentage of the day. Ex: my planner starts at 6:00, if I have an item at 15:00, that is halfway through the time frame from 6:00-24:00- So the color of that block is the color halfway between the start and end color.

**Comment by JosephBrooksbank** [comment]
Welp, that's what I get for trying to fix more line ending issues by re-cloning. Switched to different branch in fork to make things easier, will make a new PR when ready

**Comment by ivan-lednev** [comment]
Hey, @JosephBrooksbank, I misunderstood then, you've implemented exactly what I had in mind :)

**Pull request closed without merging**
