### PR TITLE
feat(rsvp based ribbon): added designs based on user RSVP for the event

### PR DESCRIPTION
**Pull request by ramandv**
https://github.com/ivan-lednev/obsidian-day-planner/pull/540

@ivan-lednev requested changes, have been done. 
Let me know if you need any clarification.

BTW, I have introduced email in the settings for remote calendar. Cos, using that only, we can figure out the user's rsvpstatus.

### CODE REVIEW

**Comment by ramandv** [comment]
@ivan-lednev let me know if you need further changes

**Comment by ivan-lednev** [comment]
Hello, @ramandv,

I'm going to hijack this PR, because it's faster to fix the issues myself than to go back and forth with the review.

Next time, do not close the previous PR once you've addressed all the comments. Update the previous PR instead and give a short answer to every question raised.

I can see at a glance that you didn't address the most important comment. I've checked my Google calendar, and I see that you can pull 'status' right from the event object:
image
So your manipulations with emails make no sense to me.

Next time, please make an effort and respect the time of the maintainer. This way I can spend more time providing value to the users instead of going back and forth with these reviews, repeating the same comments.

**Comment by ramandv** [comment]
@ivan-lednev 
I sincerely apologize for prematurely closing that pull request. I now realize how frustrating that might have been from a maintainer's perspective. I’ll make sure to keep this in mind for future contributions and be more considerate.

Regarding your question in the PR, I overlooked responding to it—my apologies. To clarify, the field you highlighted isn't the one we should be referencing for participant RSVP status.

To explain further:

**The STATUS field in the event indicates the overall status of the event, not the status of individual attendees.
For RSVP details of a specific attendee, we need to check the ATTENDEE fields, focusing on the PARTSTAT parameter, which reflects each attendee's RSVP status.**

You can check the VEVENT documentation also. 


I hope this clarifies things! Let me know if you need further details or if I can assist in any other way.

**Comment by ramandv** [comment]
@ivan-lednev 

Thank you for your response! I noticed you reacted to my previous message, and I appreciate that.

I just wanted to check in to see if you had a chance to review the explanation I provided regarding the VEVENT documentation and the PARTSTAT parameter for RSVP status. If there's anything more I can clarify or adjust to help move the pull request forward, please feel free to let me know—I'd be happy to assist.

Looking forward to hearing your thoughts!

**Comment by ivan-lednev** [comment]
I've added some fixes and merged your commits. You can see the fixes here: https://github.com/ivan-lednev/obsidian-day-planner/commit/e25026378407006d84a934521872e7635c465437

Mostly it's removing implicit `any`s and needless pseudo-elements.

**Comment by ramandv** [comment]
@ivan-lednev 
I'm glad it got merged.
BTW, I love this plugin. Every day this helps in planning my day.
 Looking forward to the next release.

**Pull request closed without merging**
